### ISSUE TITLE
Branch 3.1

### ISSUE THREAD

**Issue by thomasvargiu** [Ocramius/OcraCachedViewResolver#33]
Hi, can you create a branch `3.1`?. I would like to merge something for the older version.
In order to upgrade a project using `zendframework/zend-servicemanager` >= 3.0 with `zendframework/zend-mvc` < 3.0 I updated the code to support it, helping me to migrate my project step by step. It would be useful for a lot of projects.
I would like to merge it in a branch to future release a `3.1.0` version.

**Comment by Ocramius** [comment]
3.0 is abandoned. Unless you found a security issue in it, I will *not* merge anything into it.
