### ISSUE TITLE
Support to Zend Expressive

### ISSUE THREAD

**Issue by guilherme90** [Ocramius/OcraCachedViewResolver#34]
I use Zend Expressive and would like to use this module. How could I do it to add it to the project?

OBS: **ZE 1.x**

Thanks

**Comment by Ocramius** [comment]
This project is currently designed [for `zend-mvc`](https://github.com/Ocramius/OcraCachedViewResolver/blob/9e3315149f4b3bfba4641ea25c2d54ee0608e48e/composer.json#L23)

I don't plan to update it in the near future, as I lack the time to do so.
