### ISSUE TITLE
4.0.1 release?

### ISSUE THREAD

**Issue by thomasvargiu** [Ocramius/OcraCachedViewResolver#38]
Hi, is it possible to tag a new release for the latest commits?
I'm need to use the commit SHA in my project's composer at the moment.

**Comment by malukenho** [comment]
I think you can use the following syntax `dev-master#hash-commit-here`.

**Comment by thomasvargiu** [comment]
I’m using it like that. But in this way I can only download it from source

**Comment by Ocramius** [comment]
Doing a release now.
